-- Private backend-only schema for the FKiS demo. Tables are not accessible
-- through the Supabase Data API; the application connects server-side.
CREATE TABLE public.academic_groups (
  group_code text PRIMARY KEY,
  source text NOT NULL DEFAULT 'local',
  display_code text,
  faculty text,
  direction text,
  course integer
);

CREATE TABLE public.students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  health text NOT NULL,
  attendance integer NOT NULL DEFAULT 0,
  theory text NOT NULL DEFAULT 'не указано',
  practice text NOT NULL DEFAULT 'не указано',
  group_code text NOT NULL DEFAULT '0905' REFERENCES public.academic_groups(group_code),
  isu_id text,
  enrollment_number text,
  study_form text,
  list_position integer,
  birth_date date,
  theory_date date
);

CREATE TABLE public.attendance_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES public.students(id),
  lesson_date date NOT NULL,
  topic text NOT NULL,
  present boolean NOT NULL,
  CONSTRAINT attendance_student_lesson_unique UNIQUE(student_id, lesson_date)
);

CREATE TABLE public.achievements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES public.students(id),
  category text NOT NULL,
  details text NOT NULL,
  record_date text NOT NULL,
  status text NOT NULL DEFAULT 'Подтверждено',
  sport_type text,
  distinction text,
  age_group text,
  order_basis text,
  participant_role text,
  event_result text,
  note text,
  document_name text,
  document_data bytea,
  team_name text
);

CREATE TABLE public.physical_tests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES public.students(id),
  record_date date NOT NULL,
  exercise text NOT NULL,
  result text NOT NULL,
  CONSTRAINT physical_test_unique UNIQUE(student_id, record_date, exercise)
);

CREATE INDEX idx_attendance_student_date ON public.attendance_log(student_id, lesson_date);
CREATE INDEX idx_achievements_student ON public.achievements(student_id);
CREATE INDEX idx_students_group ON public.students(group_code);
CREATE UNIQUE INDEX idx_students_isu_id ON public.students(isu_id) WHERE isu_id IS NOT NULL;

ALTER TABLE public.academic_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.physical_tests ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.academic_groups, public.students, public.attendance_log, public.achievements, public.physical_tests FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
