let students=[],achievements=[],activeGroup=localStorage.getItem('fkis-active-group')||'12509-05',selectedStudentId=null,selectedAchievementId=null,activeDiscipline='',studentFilter='all';const $=s=>document.querySelector(s),ini=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2),short=n=>n.split(' ').slice(0,2).join(' ');
async function api(url,method='GET',body){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body&&JSON.stringify(body)});if(!r.ok)throw Error((await r.json()).error||'Ошибка сохранения');return r.json()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function status(v){return v==='зачет'||v==='Действующий'||v==='Подтверждено'?'good':v==='не зачет'?'bad':'warn'}
function render(){
 $('#studentsBody').innerHTML=students.map(s=>`<tr><td><div class="student-cell"><span class="avatar">${ini(s.name)}</span><div><b>${s.name}</b><small>${activeGroup}</small></div></div></td><td>${s.health}</td><td><span class="status ${s.attendance<70?'bad':s.attendance<80?'warn':'good'}">${s.attendance}%</span></td><td><span class="status ${status(s.theory)}">${s.theory}</span></td><td><span class="status ${status(s.practice)}">${s.practice}</span></td><td><button class="detail-button" data-student="${s.id}">Карточка</button></td></tr>`).join('');
 $('#attendanceBody').innerHTML=students.map((s,index)=>`<tr><td>${index+1}</td><td><div class="student-cell"><span class="avatar">${ini(s.name)}</span><b>${s.name}</b></div></td><td>${s.health}</td><td><div class="attendance-toggle" data-id="${s.id}"><button class="${s.present?'on':''}" data-set="true">Присутствовал</button><button class="${!s.present?'off':''}" data-set="false">Отсутствовал</button></div></td></tr>`).join('');
 $('#achievementBody').innerHTML=achievements.map(a=>`<tr><td><b>${a.name}</b></td><td>${a.category}</td><td>${a.details}</td><td>${a.record_date}</td><td><span class="status ${status(a.status)}">${a.status}</span></td><td><button class="detail-button" data-achievement="${a.id}">Изменить</button></td></tr>`).join('');
 $('#attentionList').innerHTML=students.filter(s=>s.attendance<70).map(s=>`<div class="attention-row"><span class="avatar">${ini(s.name)}</span><div><b>${short(s.name)}</b><small>${activeGroup}</small></div><span class="attendance-score">${s.attendance}%</span></div>`).join('');
 $('#achievementStudent').innerHTML=students.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');
 updateStats();
}
function updateStats(){let total=students.length||1,attention=students.filter(s=>s.attendance<70).length,theory=students.filter(s=>s.theory==='зачет').length,practice=students.filter(s=>s.practice==='зачет').length,attendance=students.filter(s=>s.attendance>=70).length,avg=Math.round(students.reduce((sum,s)=>sum+s.attendance,0)/total),health=type=>students.filter(s=>s.health===type).length,pct=value=>`${Math.round(value/total*100)}%`;$('#metricStudents').textContent=students.length;$('#metricAttendance').textContent=`${avg}%`;$('#metricCredit').textContent=`${practice} / ${students.length}`;$('#metricCreditShare').textContent=`${pct(practice)} группы`;$('#metricAttention').textContent=attention;$('#filterAll').textContent=`Все · ${students.length}`;$('#filterCredit').textContent=`Зачет · ${practice}`;$('#filterAttention').textContent=`Внимание · ${attention}`;$('#attendanceStudentCount').textContent=students.length;$('#reportMain').textContent=health('основная');$('#reportMainShare').textContent=`${pct(health('основная'))} студентов`;$('#reportPrep').textContent=health('подготовительная');$('#reportPrepShare').textContent=`${pct(health('подготовительная'))} студентов`;$('#reportSpecial').textContent=health('специальная');$('#reportSpecialShare').textContent=`${pct(health('специальная'))} студентов`;$('#reportEvents').textContent=achievements.filter(a=>a.category.includes('Мероприятие')).length;[['theory',theory],['practice',practice],['attendance',attendance]].forEach(([key,value])=>{$('#'+key+'Pass').textContent=value;$('#'+key+'Fail').textContent=students.length-value;$('#'+key+'Share').textContent=pct(value)});}
function updateGroupLabels(){document.querySelectorAll('[data-group-label]').forEach(el=>el.textContent=activeGroup);const top=$('#topGroupName');if(top)top.textContent=activeGroup}
async function load(){let d=await api(`/api/bootstrap?group=${encodeURIComponent(activeGroup)}`);activeGroup=d.group||activeGroup;updateGroupLabels();students=d.students.map(s=>({...s,present:!!s.present}));achievements=d.achievements;render()}
window.setActiveGroup=group=>{activeGroup=group;localStorage.setItem('fkis-active-group',group);updateGroupLabels();load().catch(()=>toast('Не удалось открыть данные группы.'))};
function resetAttendanceFlow(){activeDiscipline='';$('#disciplineSelect').value='';$('#attendanceSetup').hidden=false;$('#attendanceJournal').hidden=true;$('#saveAttendance').hidden=true;$('#attendanceSubtitle').innerHTML=`Группа <span data-group-label>${activeGroup}</span> · выберите дисциплину`;updateGroupLabels()}
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$('#'+v).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='attendance')resetAttendanceFlow();window.placeGroupPicker?.();scrollTo({top:0,behavior:'smooth'})}
function card(id){let s=students.find(x=>x.id===+id);selectedStudentId=s.id;$('#modalStudentName').textContent=s.name;$('#studentDetails').innerHTML=`<div class="detail-grid"><div><span>Учебная группа</span><b>${activeGroup}</b></div><div><span>Группа здоровья</span><b>${s.health}</b></div><div><span>Посещаемость</span><b>${s.attendance}%</b></div><div><span>Теория и методика</span><b>${s.theory}</b></div><div><span>Практика ФКиС</span><b>${s.practice}</b></div><div><span>Достижения</span><b>${achievements.filter(a=>a.name===s.name).length||'нет сведений'}</b></div></div>`;$('#studentModal').hidden=false}
function editAchievement(id){let a=achievements.find(x=>x.id===+id);selectedAchievementId=a.id;$('#editAchievementStudent').innerHTML=students.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('#editAchievementStudent').value=a.student_id;$('#editAchievementCategory').value=a.category;$('#editAchievementDetails').value=a.details;$('#editAchievementDate').value=a.record_date;$('#editAchievementStatus').value=a.status;$('#achievementEditModal').hidden=false}
function applyStudentFilter(){document.querySelectorAll('#studentsBody tr').forEach((row,index)=>{let s=students[index];row.hidden=studentFilter==='credit'?s.practice!=='зачет':studentFilter==='attention'?s.attendance>=70:false})}
document.addEventListener('click',async e=>{let n=e.target.closest('.nav-item'),g=e.target.closest('[data-go]'),d=e.target.closest('[data-student]'),a=e.target.closest('[data-achievement]'),f=e.target.closest('[data-student-filter]'),c=e.target.closest('[data-close]'),set=e.target.closest('[data-set]');if(n)go(n.dataset.view);if(g)go(g.dataset.go);if(d)card(d.dataset.student);if(a)editAchievement(a.dataset.achievement);if(f){studentFilter=f.dataset.studentFilter;document.querySelectorAll('[data-student-filter]').forEach(button=>button.classList.toggle('active',button===f));applyStudentFilter()}if(c)$('#'+c.dataset.close).hidden=true;if(set){students.find(x=>x.id===+set.parentElement.dataset.id).present=set.dataset.set==='true';render()}});
$('#studentSearch').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('#studentsBody tr').forEach((r,i)=>r.hidden=!students[i].name.toLowerCase().includes(q))};
$('#confirmDiscipline').onclick=()=>{let discipline=$('#disciplineSelect').value;if(!discipline)return toast('Сначала выберите дисциплину.');activeDiscipline=discipline;$('#activeDisciplineLabel').textContent=discipline;$('#attendanceSubtitle').innerHTML=`Группа <span data-group-label>${activeGroup}</span> · ${discipline}`;updateGroupLabels();$('#attendanceSetup').hidden=true;$('#attendanceJournal').hidden=false;$('#saveAttendance').hidden=false;toast('Журнал открыт для отметки посещаемости.');};
$('#changeDiscipline').onclick=resetAttendanceFlow;
$('#saveAttendance').onclick=async()=>{if(!activeDiscipline)return toast('Сначала выберите дисциплину.');try{await api('/api/attendance','POST',{lesson_date:$('#lessonDate').value,topic:activeDiscipline,items:students.map(s=>({id:s.id,present:s.present}))});toast('Отметки сохранены в SQLite.')}catch(e){toast(e.message)}};
$('#openAchievement').onclick=()=>$('#achievementModal').hidden=false;$('#saveAchievement').onclick=async()=>{let x=$('#achievementDetails').value.trim();if(!x)return toast('Заполни сведения о достижении.');try{await api('/api/achievements','POST',{student_id:+$('#achievementStudent').value,category:$('#achievementCategory').value,details:x});$('#achievementModal').hidden=true;$('#achievementDetails').value='';await load();toast('Достижение добавлено в SQLite.')}catch(e){toast(e.message)}};
$('#editStudent').onclick=()=>{let s=students.find(x=>x.id===selectedStudentId);if(!s)return;$('#editStudentName').value=s.name;$('#editStudentHealth').value=s.health;$('#editStudentAttendance').value=s.attendance;$('#editStudentTheory').value=s.theory;$('#editStudentPractice').value=s.practice;$('#studentModal').hidden=true;$('#studentEditModal').hidden=false};
$('#saveStudentEdit').onclick=async()=>{let name=$('#editStudentName').value.trim(),attendance=+$('#editStudentAttendance').value;if(name.split(' ').length<2||attendance<0||attendance>100)return toast('Проверьте ФИО и посещаемость.');try{await api(`/api/students/${selectedStudentId}`,'PUT',{name,health:$('#editStudentHealth').value,attendance,theory:$('#editStudentTheory').value,practice:$('#editStudentPractice').value});$('#studentEditModal').hidden=true;await load();toast('Данные студента сохранены.')}catch(e){toast(e.message)}};
$('#saveAchievementEdit').onclick=async()=>{let details=$('#editAchievementDetails').value.trim();if(!details)return toast('Заполните сведения о достижении.');try{await api(`/api/achievements/${selectedAchievementId}`,'PUT',{student_id:+$('#editAchievementStudent').value,category:$('#editAchievementCategory').value,details,record_date:$('#editAchievementDate').value.trim(),status:$('#editAchievementStatus').value});$('#achievementEditModal').hidden=true;await load();toast('Достижение сохранено.')}catch(e){toast(e.message)}};
$('#addStudent').onclick=()=>$('#addStudentModal').hidden=false;$('#saveStudent').onclick=async()=>{let n=$('#newStudentName').value.trim();if(n.split(' ').length<2)return toast('Укажи фамилию и имя.');try{await api('/api/students','POST',{name:n,health:$('#newStudentHealth').value,group_code:activeGroup});$('#addStudentModal').hidden=true;$('#newStudentName').value='';await load();toast('Студент добавлен в SQLite.')}catch(e){toast(e.message)}};
$('#exportReport').onclick=()=>{window.location.href=`/api/export.xlsx?group=${encodeURIComponent(activeGroup)}`;toast('Excel-ведомость подготовлена.')};
let tour=[{view:'dashboard',target:'.metric-grid',title:'Рабочее место преподавателя',text:'На главном экране сразу видны показатели группы и студенты, которым нужно уделить внимание.'},{view:'attendance',target:'.journal',title:'Журнал занятия',text:'Выберите дату и тему, затем отметьте присутствие каждого студента. Одно сохранение обновляет тестовую базу.'},{view:'students',target:'.detail-button',title:'Карточка студента',text:'Нажмите «Карточка» напротив студента, чтобы увидеть все сведения по нему.'},{view:'achievements',target:'.achievement-tabs',title:'Достижения',text:'Здесь учитываются ГТО, спортивные разряды и мероприятия. Вкладки отфильтруют записи по типу.'}],step=0;
function placeTourSpotlight(){let item=tour[step],target=document.querySelector(`#${item.view} ${item.target}`),spot=$('#tourSpotlight');if(!target)return;let r=target.getBoundingClientRect(),pad=8;spot.style.left=`${Math.max(6,r.left-pad)}px`;spot.style.top=`${Math.max(6,r.top-pad)}px`;spot.style.width=`${Math.min(innerWidth-12,r.width+pad*2)}px`;spot.style.height=`${Math.min(innerHeight-12,r.height+pad*2)}px`}
function guide(){let item=tour[step];go(item.view);$('#tourTitle').textContent=item.title;$('#tourText').textContent=item.text;$('#tourCount').textContent=`${step+1} из ${tour.length}`;$('#tourNext').textContent=step===tour.length-1?'Готово':'Далее';$('#tourMask').hidden=false;requestAnimationFrame(()=>requestAnimationFrame(placeTourSpotlight))}
function closeGuide(){$('#tourMask').hidden=true;$('#tourSpotlight').removeAttribute('style')}
['guideStart','noticeGuide'].forEach(id=>$('#'+id).onclick=()=>{step=0;guide()});$('#tourNext').onclick=()=>{step===tour.length-1?closeGuide():(step++,guide())};['tourSkip','closeTour'].forEach(id=>$('#'+id).onclick=closeGuide);addEventListener('resize',()=>!$('#tourMask').hidden&&placeTourSpotlight());$('#roleButton').onclick=()=>toast('Роль: преподаватель. В полном сервисе будет вход через ИСУ.');load().catch(()=>toast('Не удалось открыть SQLite.'));
