const students = [
  ['Александрова Мария Игоревна','основная',92,'зачет','зачет'],['Белов Кирилл Денисович','основная',86,'зачет','зачет'],['Васильева Елизавета Сергеевна','подготовительная',78,'зачет','зачет'],['Гром Никита Олегович','основная',95,'зачет','зачет'],['Данилов Артём Максимович','основная',68,'зачет','не зачет'],['Егорова Полина Вадимовна','основная',88,'зачет','зачет'],['Жуков Андрей Петрович','специальная',72,'зачет','зачет'],['Зайцева Ксения Романовна','основная',91,'зачет','зачет'],['Иванов Илья Андреевич','основная',96,'зачет','зачет'],['Калинин Максим Олегович','подготовительная',83,'зачет','зачет'],['Кириллова Дарья Николаевна','основная',89,'зачет','зачет'],['Козлов Михаил Аркадьевич','основная',64,'не зачет','не зачет'],['Комарова Софья Павловна','основная',90,'зачет','зачет'],['Кузнецов Денис Викторович','подготовительная',75,'зачет','зачет'],['Лебедева Анна Дмитриевна','основная',87,'зачет','зачет'],['Мельникова Виктория Олеговна','основная',93,'зачет','зачет'],['Морозов Павел Андреевич','основная',69,'зачет','не зачет'],['Николаева Арина Максимовна','специальная',76,'зачет','зачет'],['Орлов Владислав Сергеевич','основная',85,'зачет','зачет'],['Павлова Кира Алексеевна','подготовительная',82,'зачет','зачет'],['Петров Арсений Владиславович','основная',89,'зачет','зачет'],['Романова Вероника Олеговна','основная',94,'зачет','зачет'],['Смирнов Егор Ильич','основная',66,'не зачет','не зачет'],['Соколова Алиса Дмитриевна','подготовительная',80,'зачет','зачет'],['Тарасов Матвей Романович','основная',88,'зачет','зачет'],['Фёдорова Ева Максимовна','основная',91,'зачет','зачет'],['Харитонов Лев Евгеньевич','подготовительная',74,'зачет','зачет'],['Чернова Алина Викторовна','основная',87,'зачет','зачет']
].map((s,i)=>({id:i+1,name:s[0],health:s[1],attendance:s[2],theory:s[3],practice:s[4],present:i!==4&&i!==11&&i!==16&&i!==22}));
const achievements=[['Иванов Илья Андреевич','Спортивный разряд','Мастер спорта · мини-футбол','12.09.2026','Действующий'],['Гром Никита Олегович','ВФСК «ГТО»','Золотой знак · VII ступень','10.09.2026','Подтверждено'],['Александрова Мария Игоревна','Мероприятие','Участник · Спартакиада СПбГМТУ','08.09.2026','Подтверждено'],['Петров Арсений Владиславович','Мероприятие','Волонтер · День спорта','05.09.2026','Подтверждено'],['Кузнецов Денис Викторович','Спортивный разряд','КМС · плавание','01.09.2026','Действующий']];
const initials=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2); const short=n=>n.split(' ').slice(0,2).join(' ');
function studentRows(list=students){document.querySelector('#studentsBody').innerHTML=list.map(s=>`<tr><td><div class="student-cell"><span class="avatar">${initials(s.name)}</span><div><b>${s.name}</b><small>12509-05</small></div></div></td><td>${s.health}</td><td><span class="status ${s.attendance<70?'bad':s.attendance<80?'warn':'good'}">${s.attendance}%</span></td><td><span class="status ${s.theory==='зачет'?'good':'bad'}">${s.theory}</span></td><td><span class="status ${s.practice==='зачет'?'good':'bad'}">${s.practice}</span></td><td><button class="detail-button" data-student="${s.id}">Карточка</button></td></tr>`).join('')}
function attendanceRows(){document.querySelector('#attendanceBody').innerHTML=students.map(s=>`<tr><td>${s.id}</td><td><div class="student-cell"><span class="avatar">${initials(s.name)}</span><b>${s.name}</b></div></td><td>${s.health}</td><td><div class="attendance-toggle" data-id="${s.id}"><button class="${s.present?'on':''}" data-set="true">Присутствовал</button><button class="${!s.present?'off':''}" data-set="false">Отсутствовал</button></div></td></tr>`).join('')}
function achievementRows(){document.querySelector('#achievementBody').innerHTML=achievements.map(a=>`<tr><td><b>${a[0]}</b><small class="mobile-small">12509-05</small></td><td>${a[1]}</td><td>${a[2]}</td><td>${a[3]}</td><td><span class="status good">${a[4]}</span></td></tr>`).join('')}
function attentionRows(){document.querySelector('#attentionList').innerHTML=students.filter(s=>s.attendance<70).map(s=>`<div class="attention-row"><span class="avatar">${initials(s.name)}</span><div><b>${short(s.name)}</b><small>12509-05</small></div><span class="attendance-score">${s.attendance}%</span></div>`).join('')}
function showToast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function go(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));document.querySelector('#'+view).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function openStudent(id){const s=students.find(x=>x.id===+id);document.querySelector('#modalStudentName').textContent=s.name;document.querySelector('#studentDetails').innerHTML=`<div class="detail-grid"><div><span>Учебная группа</span><b>12509-05</b></div><div><span>Группа здоровья</span><b>${s.health}</b></div><div><span>Посещаемость</span><b>${s.attendance}%</b></div><div><span>Теория и методика</span><b>${s.theory}</b></div><div><span>Практика ФКиС</span><b>${s.practice}</b></div><div><span>ВФСК «ГТО»</span><b>${id===4?'золотой знак':'нет сведений'}</b></div></div>`;document.querySelector('#studentModal').hidden=false}
const tour=[['Рабочее место преподавателя','На главном экране сразу видны группа, показатели посещаемости и студенты, которым нужно уделить внимание.'],['Журнал занятия','Выберите дату и тему, затем отметьте присутствие каждого студента. Одно сохранение обновляет показатели группы.'],['Карточка студента','Нажмите «Карточка» в списке, чтобы увидеть учебные результаты, здоровье, посещаемость и спортивные сведения.'],['Достижения и сводка','Сотрудник ССК добавляет ГТО, разряды и мероприятия. В сводке руководитель видит результаты группы.']];let tourStep=0;function renderTour(){const [a,b]=tour[tourStep];document.querySelector('#tourTitle').textContent=a;document.querySelector('#tourText').textContent=b;document.querySelector('#tourCount').textContent=`${tourStep+1} из ${tour.length}`;document.querySelector('#tourNext').textContent=tourStep===tour.length-1?'Готово':'Далее';document.querySelector('#tourMask').hidden=false}
studentRows();attendanceRows();achievementRows();attentionRows();document.querySelector('#achievementStudent').innerHTML=students.map(s=>`<option>${s.name}</option>`).join('');
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item');if(nav)go(nav.dataset.view);const target=e.target.closest('[data-go]');if(target)go(target.dataset.go);const detail=e.target.closest('[data-student]');if(detail)openStudent(detail.dataset.student);const close=e.target.closest('[data-close]');if(close)document.querySelector('#'+close.dataset.close).hidden=true;const set=e.target.closest('[data-set]');if(set){const id=+set.parentElement.dataset.id;students.find(s=>s.id===id).present=set.dataset.set==='true';attendanceRows()} });
document.querySelector('#studentSearch').addEventListener('input',e=>studentRows(students.filter(s=>s.name.toLowerCase().includes(e.target.value.toLowerCase()))));
document.querySelector('#saveAttendance').addEventListener('click',()=>showToast('Отметки сохранены. Сводка группы обновлена.'));
document.querySelector('#openAchievement').addEventListener('click',()=>document.querySelector('#achievementModal').hidden=false);
document.querySelector('#saveAchievement').addEventListener('click',()=>{achievements.unshift([document.querySelector('#achievementStudent').value,'ВФСК «ГТО»','Золотой знак · тестовая запись','16.09.2026','Подтверждено']);achievementRows();document.querySelector('#achievementModal').hidden=true;showToast('Достижение добавлено в карточку студента.')});
document.querySelector('#addStudent').addEventListener('click',()=>showToast('В MVP новые студенты поступают из тестовой базы.'));document.querySelector('#exportReport').addEventListener('click',()=>showToast('Файл сводки подготовлен (демонстрация).'));document.querySelector('#roleButton').addEventListener('click',()=>showToast('Роль: преподаватель. В полном сервисе будет вход через ИСУ.'));
['guideStart','noticeGuide'].forEach(id=>document.querySelector('#'+id).addEventListener('click',()=>{tourStep=0;renderTour()}));document.querySelector('#tourNext').addEventListener('click',()=>{if(tourStep===tour.length-1){document.querySelector('#tourMask').hidden=true;return}tourStep++;renderTour()});['tourSkip','closeTour'].forEach(id=>document.querySelector('#'+id).addEventListener('click',()=>document.querySelector('#tourMask').hidden=true));document.querySelector('#changeGroup').addEventListener('click',()=>showToast('Другие группы появятся после подключения ИСУ.'));
