let students=[],achievements=[];const $=s=>document.querySelector(s),ini=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2),short=n=>n.split(' ').slice(0,2).join(' ');
async function api(url,method='GET',body){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body&&JSON.stringify(body)});if(!r.ok)throw Error((await r.json()).error||'Ошибка сохранения');return r.json()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function status(v){return v==='зачет'||v==='Действующий'||v==='Подтверждено'?'good':v==='не зачет'?'bad':'warn'}
function render(){
 $('#studentsBody').innerHTML=students.map(s=>`<tr><td><div class="student-cell"><span class="avatar">${ini(s.name)}</span><div><b>${s.name}</b><small>12509-05</small></div></div></td><td>${s.health}</td><td><span class="status ${s.attendance<70?'bad':s.attendance<80?'warn':'good'}">${s.attendance}%</span></td><td><span class="status ${status(s.theory)}">${s.theory}</span></td><td><span class="status ${status(s.practice)}">${s.practice}</span></td><td><button class="detail-button" data-student="${s.id}">Карточка</button></td></tr>`).join('');
 $('#attendanceBody').innerHTML=students.map(s=>`<tr><td>${s.id}</td><td><div class="student-cell"><span class="avatar">${ini(s.name)}</span><b>${s.name}</b></div></td><td>${s.health}</td><td><div class="attendance-toggle" data-id="${s.id}"><button class="${s.present?'on':''}" data-set="true">Присутствовал</button><button class="${!s.present?'off':''}" data-set="false">Отсутствовал</button></div></td></tr>`).join('');
 $('#achievementBody').innerHTML=achievements.map(a=>`<tr><td><b>${a.name}</b></td><td>${a.category}</td><td>${a.details}</td><td>${a.record_date}</td><td><span class="status ${status(a.status)}">${a.status}</span></td></tr>`).join('');
 $('#attentionList').innerHTML=students.filter(s=>s.attendance<70).map(s=>`<div class="attention-row"><span class="avatar">${ini(s.name)}</span><div><b>${short(s.name)}</b><small>12509-05</small></div><span class="attendance-score">${s.attendance}%</span></div>`).join('');
 $('#achievementStudent').innerHTML=students.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');
}
async function load(){let d=await api('/api/bootstrap');students=d.students.map(s=>({...s,present:!!s.present}));achievements=d.achievements;render()}
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$('#'+v).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));scrollTo({top:0,behavior:'smooth'})}
function card(id){let s=students.find(x=>x.id===+id);$('#modalStudentName').textContent=s.name;$('#studentDetails').innerHTML=`<div class="detail-grid"><div><span>Учебная группа</span><b>12509-05</b></div><div><span>Группа здоровья</span><b>${s.health}</b></div><div><span>Посещаемость</span><b>${s.attendance}%</b></div><div><span>Теория и методика</span><b>${s.theory}</b></div><div><span>Практика ФКиС</span><b>${s.practice}</b></div><div><span>Достижения</span><b>${achievements.filter(a=>a.name===s.name).length||'нет сведений'}</b></div></div>`;$('#studentModal').hidden=false}
document.addEventListener('click',async e=>{let n=e.target.closest('.nav-item'),g=e.target.closest('[data-go]'),d=e.target.closest('[data-student]'),c=e.target.closest('[data-close]'),set=e.target.closest('[data-set]');if(n)go(n.dataset.view);if(g)go(g.dataset.go);if(d)card(d.dataset.student);if(c)$('#'+c.dataset.close).hidden=true;if(set){students.find(x=>x.id===+set.parentElement.dataset.id).present=set.dataset.set==='true';render()}});
$('#studentSearch').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('#studentsBody tr').forEach((r,i)=>r.hidden=!students[i].name.toLowerCase().includes(q))};
$('#saveAttendance').onclick=async()=>{try{await api('/api/attendance','POST',{lesson_date:$('#lessonDate').value,topic:$('#lessonTopic').value,items:students.map(s=>({id:s.id,present:s.present}))});toast('Отметки сохранены в SQLite.')}catch(e){toast(e.message)}};
$('#openAchievement').onclick=()=>$('#achievementModal').hidden=false;$('#saveAchievement').onclick=async()=>{let x=$('#achievementDetails').value.trim();if(!x)return toast('Заполни сведения о достижении.');try{await api('/api/achievements','POST',{student_id:+$('#achievementStudent').value,category:$('#achievementCategory').value,details:x});$('#achievementModal').hidden=true;$('#achievementDetails').value='';await load();toast('Достижение добавлено в SQLite.')}catch(e){toast(e.message)}};
$('#addStudent').onclick=()=>$('#addStudentModal').hidden=false;$('#saveStudent').onclick=async()=>{let n=$('#newStudentName').value.trim();if(n.split(' ').length<2)return toast('Укажи фамилию и имя.');try{await api('/api/students','POST',{name:n,health:$('#newStudentHealth').value});$('#addStudentModal').hidden=true;$('#newStudentName').value='';await load();toast('Студент добавлен в SQLite.')}catch(e){toast(e.message)}};
$('#exportReport').onclick=()=>{window.location.href='/api/export.xlsx';toast('Excel-ведомость подготовлена.')};
let tour=[['Рабочее место преподавателя','На главном экране сразу видны группа, показатели посещаемости и студенты, которым нужно уделить внимание.'],['Журнал занятия','Выберите дату и тему, затем отметьте присутствие каждого студента. Одно сохранение обновляет SQLite.'],['Карточка студента','Нажмите «Карточка» в списке, чтобы увидеть все сведения.'],['Достижения и сводка','ССК добавляет ГТО, разряды и мероприятия. Записи сохраняются в тестовой базе.']],step=0;function guide(){let [a,b]=tour[step];$('#tourTitle').textContent=a;$('#tourText').textContent=b;$('#tourCount').textContent=`${step+1} из 4`;$('#tourNext').textContent=step===3?'Готово':'Далее';$('#tourMask').hidden=false}['guideStart','noticeGuide'].forEach(id=>$('#'+id).onclick=()=>{step=0;guide()});$('#tourNext').onclick=()=>{step===3?$('#tourMask').hidden=true:(step++,guide())};['tourSkip','closeTour'].forEach(id=>$('#'+id).onclick=()=>$('#tourMask').hidden=true);$('#roleButton').onclick=()=>toast('Роль: преподаватель. В полном сервисе будет вход через ИСУ.');$('#changeGroup').onclick=()=>toast('В тестовом контуре доступна группа 12509-05.');load().catch(()=>toast('Не удалось открыть SQLite.'));
